### ISSUE TITLE
Cannot build with streaming-0.2

### ISSUE THREAD

**Issue by ocharles** [ivan-m/streaming-concurrency#2]

**Comment by ivan-m** [comment]
That would be because I didn't know about streaming-0.2 being released!

I'm currently trying to benchmark and find an optimal implementation of `withStreamMap{,M}`; do you mind if I wait a few days before releasing a fix for the dependency bump to try and track down the best mapping implementation?

**Comment by ocharles** [comment]
Sure, for now I can install by ignoring bounds.

**Comment by ivan-m** [comment]
Sorry it took me so long but it's released now as 0.3.1.0;  I kept trying to tweak the benchmarking code in the hopes of getting an optimal solution but in the end just picked one.
